[build]
  publish = "public"
  functions = "netlify/functions"

[dev]
  command = "echo 'No build step needed'"
  port = 8888

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions.rapport]
  timeout = 26
